// <auto-generated />
using HotelListing.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HotelListing.API.Migrations
{
    [DbContext(typeof(HotelListingDbContext))]
    partial class HotelListingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.15");

            modelBuilder.Entity("HotelListing.API.Data.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "FR",
                            Name = "France"
                        },
                        new
                        {
                            Id = 2,
                            Code = "ES",
                            Name = "Spain"
                        },
                        new
                        {
                            Id = 3,
                            Code = "US",
                            Name = "United States"
                        },
                        new
                        {
                            Id = 4,
                            Code = "TR",
                            Name = "Turkiye"
                        },
                        new
                        {
                            Id = 5,
                            Code = "IT",
                            Name = "Italy"
                        },
                        new
                        {
                            Id = 6,
                            Code = "MX",
                            Name = "Mexico"
                        },
                        new
                        {
                            Id = 7,
                            Code = "UK",
                            Name = "United Kingdom"
                        },
                        new
                        {
                            Id = 8,
                            Code = "DE",
                            Name = "Germany"
                        },
                        new
                        {
                            Id = 9,
                            Code = "GR",
                            Name = "Greece"
                        },
                        new
                        {
                            Id = 10,
                            Code = "AT",
                            Name = "Austria"
                        });
                });

            modelBuilder.Entity("HotelListing.API.Data.Hotel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<int>("CountryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<double>("Rating")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Hotels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "4499 Rond-point Des Lilas, 21597 Albi",
                            CountryId = 1,
                            Name = "Encantar Fuga",
                            Rating = 4.7000000000000002
                        },
                        new
                        {
                            Id = 2,
                            Address = "55 Pont d'Orsel, 62980 Perigueux",
                            CountryId = 1,
                            Name = "Luxo Opulento",
                            Rating = 4.9000000000000004
                        },
                        new
                        {
                            Id = 3,
                            Address = "73 Chaussée d'Orsel, 73904 Athis-Mons",
                            CountryId = 1,
                            Name = "Luar Adornado",
                            Rating = 5.0
                        },
                        new
                        {
                            Id = 4,
                            Address = "",
                            CountryId = 1,
                            Name = "Tranquilidade Radiante",
                            Rating = 4.5999999999999996
                        },
                        new
                        {
                            Id = 5,
                            Address = "812 Dreve Boutard, 20394 Le Tampon",
                            CountryId = 1,
                            Name = "Sussurro Sofisticado",
                            Rating = 4.5999999999999996
                        },
                        new
                        {
                            Id = 6,
                            Address = "",
                            CountryId = 1,
                            Name = "Oasis Adornado",
                            Rating = 4.7999999999999998
                        },
                        new
                        {
                            Id = 7,
                            Address = "318 Passage Du Guichet, 80079 Malakoff",
                            CountryId = 1,
                            Name = "Fuga Elegante",
                            Rating = 4.5
                        },
                        new
                        {
                            Id = 8,
                            Address = "585 Traboule De Colombes, 93551 Vaulx-en-Velin",
                            CountryId = 1,
                            Name = "Regal Bliss",
                            Rating = 4.2999999999999998
                        },
                        new
                        {
                            Id = 9,
                            Address = "7 Cours La Cote des Amandiers, 85974 Lievin",
                            CountryId = 1,
                            Name = "Felicidade Real",
                            Rating = 4.5
                        },
                        new
                        {
                            Id = 10,
                            Address = "46 Chemin D'Argenteuil, 26982 Bobigny",
                            CountryId = 1,
                            Name = "Majestade Paradiso",
                            Rating = 4.5999999999999996
                        },
                        new
                        {
                            Id = 11,
                            Address = "Esc. 535 Lugar Antonia Baeza 99 Esc. 103, Algeciras, And 11640",
                            CountryId = 2,
                            Name = "Hotel Costa del Mar",
                            Rating = 4.9000000000000004
                        },
                        new
                        {
                            Id = 12,
                            Address = "Rambla Emilio, 76, Motril, Can 07669",
                            CountryId = 2,
                            Name = "Templo de la Rosa Resort",
                            Rating = 4.9000000000000004
                        },
                        new
                        {
                            Id = 13,
                            Address = "Esc. 378 Lugar Jose Emilio Arce, 6, Valladolid, Mur 40953",
                            CountryId = 2,
                            Name = "Hotel Sunny Petalo",
                            Rating = 4.9000000000000004
                        },
                        new
                        {
                            Id = 14,
                            Address = "Esc. 160 Explanada Teodoro Cardenas, 9, Alcoy, Mur 64922",
                            CountryId = 2,
                            Name = "Motel historico de Vale",
                            Rating = 4.7000000000000002
                        },
                        new
                        {
                            Id = 15,
                            Address = "Extrarradio Adela, 15, Santander, Nav 01987",
                            CountryId = 2,
                            Name = "Panorama Hotel & Spa",
                            Rating = 5.0
                        },
                        new
                        {
                            Id = 16,
                            Address = "Poligono Laura 1 Esc. 539, Torrejon de Ardoz, Cbr 51884",
                            CountryId = 2,
                            Name = "Hotel Pacifico",
                            Rating = 4.5
                        },
                        new
                        {
                            Id = 17,
                            Address = "Puerta 647 Colonia Mateo Toledo 54, Torrelavega, Rio 00109",
                            CountryId = 2,
                            Name = "Exaltado Manor Resort",
                            Rating = 4.7000000000000002
                        },
                        new
                        {
                            Id = 18,
                            Address = "Puerta 573 Ronda Maria Jose Montemayor 4, Estepona, Mur 68351",
                            CountryId = 2,
                            Name = "Hotel Lobo Supremo",
                            Rating = 4.5999999999999996
                        },
                        new
                        {
                            Id = 19,
                            Address = "Esc. 381 Pasaje Adela, 68 Puerta 893, Cornella de Llobregat, Nav 91188",
                            CountryId = 2,
                            Name = "Galaxia Resort & Spa",
                            Rating = 4.7999999999999998
                        },
                        new
                        {
                            Id = 20,
                            Address = "Puerta 757 Partida Marisol Aragon 2, Molina de Segura, Com 00279",
                            CountryId = 2,
                            Name = "Hotel Troposfera",
                            Rating = 4.5
                        },
                        new
                        {
                            Id = 21,
                            Address = "554 Gutmann Shoal, Raynorfort, NC 78628",
                            CountryId = 3,
                            Name = "Enchant Escape",
                            Rating = 4.9000000000000004
                        },
                        new
                        {
                            Id = 22,
                            Address = "97036 Paucek Meadows, Cristshire, SD 58309",
                            CountryId = 3,
                            Name = "Opulent Luxe",
                            Rating = 4.2999999999999998
                        },
                        new
                        {
                            Id = 23,
                            Address = "5257 Emard Streets, North Fredericfurt, AK 80005-7767",
                            CountryId = 3,
                            Name = "Adorned Moonlight",
                            Rating = 4.7999999999999998
                        },
                        new
                        {
                            Id = 24,
                            Address = "768 Vandervort Station, Port Moshe, LA 44351-4421",
                            CountryId = 3,
                            Name = "Radiant Tranquility",
                            Rating = 4.9000000000000004
                        },
                        new
                        {
                            Id = 25,
                            Address = "8445 Miller Hill, Lake Oliver, DE 01809-4728",
                            CountryId = 3,
                            Name = "Sophisticated Whisper",
                            Rating = 4.4000000000000004
                        },
                        new
                        {
                            Id = 26,
                            Address = "581 Donovan Common, South Douglassstad, MS 22045",
                            CountryId = 3,
                            Name = "Adorned Oasis",
                            Rating = 4.9000000000000004
                        },
                        new
                        {
                            Id = 27,
                            Address = "95400 Melany Ferry, East Hectorshire, AR 33483",
                            CountryId = 3,
                            Name = "Elegant Escape",
                            Rating = 4.7999999999999998
                        },
                        new
                        {
                            Id = 28,
                            Address = "Suite 140 6063 Erna View, Port Lashandaberg, AK 11528-8440",
                            CountryId = 3,
                            Name = "Regal Bliss",
                            Rating = 4.7999999999999998
                        },
                        new
                        {
                            Id = 29,
                            Address = "656 Tristan Passage, Ricemouth, IN 13748-6171",
                            CountryId = 3,
                            Name = "Fusion Summer",
                            Rating = 4.2999999999999998
                        },
                        new
                        {
                            Id = 30,
                            Address = "7966 Preston Meadows, West Maurita, NC 68934",
                            CountryId = 3,
                            Name = "Majesty Paradise",
                            Rating = 4.5999999999999996
                        },
                        new
                        {
                            Id = 31,
                            Address = "Umurbey Street, Konak, Izmir 35230",
                            CountryId = 4,
                            Name = "Beyaz Safari Hotel",
                            Rating = 4.7000000000000002
                        },
                        new
                        {
                            Id = 32,
                            Address = "Aydintepe Road, Tuzla, Istanbul 34944",
                            CountryId = 4,
                            Name = "Grand Tide Hotel",
                            Rating = 4.2999999999999998
                        },
                        new
                        {
                            Id = 33,
                            Address = "Ortamahalle Place, Bayrampasa, Istanbul 34030",
                            CountryId = 4,
                            Name = "Prizma Tatil Hotel",
                            Rating = 4.4000000000000004
                        },
                        new
                        {
                            Id = 34,
                            Address = "Cumhuriyet Gardens, Kas, Antalya 07960",
                            CountryId = 4,
                            Name = "Ruyalar Regency Hotel",
                            Rating = 4.7000000000000002
                        },
                        new
                        {
                            Id = 35,
                            Address = "Soguk Cesme Hill, Fatih, Istanbul 34122",
                            CountryId = 4,
                            Name = "Grandiose Castle Resort",
                            Rating = 4.9000000000000004
                        },
                        new
                        {
                            Id = 36,
                            Address = "Yunus Emre Plaza, Meram, Konya, 42090",
                            CountryId = 4,
                            Name = "Yuce Ayna Hotel",
                            Rating = 4.7999999999999998
                        },
                        new
                        {
                            Id = 37,
                            Address = "Eryaman Ayas Parkway, Etimesgut, Ankara 06790",
                            CountryId = 4,
                            Name = "Atlantis Korusu Hotel",
                            Rating = 5.0
                        },
                        new
                        {
                            Id = 38,
                            Address = "Yanarsu Junction, Bornova, Izmir 35070",
                            CountryId = 4,
                            Name = "Doga Tesisi Hotel",
                            Rating = 4.7000000000000002
                        },
                        new
                        {
                            Id = 39,
                            Address = "Kocatepe Crossing, Bayrampasa, Istanbul 34040",
                            CountryId = 4,
                            Name = "Fantezi Hotel",
                            Rating = 4.2999999999999998
                        },
                        new
                        {
                            Id = 40,
                            Address = "Kusadasi Port Street, Kusadasi, Aydin 09400",
                            CountryId = 4,
                            Name = "Uclu Zirve Spa Resort",
                            Rating = 4.5999999999999996
                        },
                        new
                        {
                            Id = 41,
                            Address = "Strada Samuel 2, Valdo lido, PI 73130",
                            CountryId = 5,
                            Name = "Esaltato Palazzo Resort",
                            Rating = 4.5999999999999996
                        },
                        new
                        {
                            Id = 42,
                            Address = "Borgo Rosolino 6, Piano 8, Testa a mare, IM 53811",
                            CountryId = 5,
                            Name = "Pinnacolo Zaffiro Hotel",
                            Rating = 4.5999999999999996
                        },
                        new
                        {
                            Id = 43,
                            Address = "",
                            CountryId = 5,
                            Name = "Resort Elegante",
                            Rating = 4.2999999999999998
                        },
                        new
                        {
                            Id = 44,
                            Address = "Contrada Sala 4, Sabatino nell'emilia, PE 46584",
                            CountryId = 5,
                            Name = "Albergo Lunare",
                            Rating = 4.7000000000000002
                        },
                        new
                        {
                            Id = 45,
                            Address = "Rotonda Fulvio 40, Piano 4, Mancini terme, LU 70629",
                            CountryId = 5,
                            Name = "Riposo Resort",
                            Rating = 4.4000000000000004
                        },
                        new
                        {
                            Id = 46,
                            Address = "Rotonda Tazio 6, Ross del friuli, SI 60618",
                            CountryId = 5,
                            Name = "Albergo Polvere di Stelle",
                            Rating = 4.5
                        },
                        new
                        {
                            Id = 47,
                            Address = "Contrada Matteo 5, Borgo Jole terme, CE 44862",
                            CountryId = 5,
                            Name = "Esaltato Star Hotel",
                            Rating = 4.9000000000000004
                        },
                        new
                        {
                            Id = 48,
                            Address = "Borgo Pellegrino 38, Piano 1, Furio ligure, OG 16690",
                            CountryId = 5,
                            Name = "Regale Lion Hotel",
                            Rating = 4.7999999999999998
                        },
                        new
                        {
                            Id = 49,
                            Address = "Via Adriano 98, Quarto Aroldo sardo, SO 15971",
                            CountryId = 5,
                            Name = "Scogliera Smeraldo Resort",
                            Rating = 4.5999999999999996
                        },
                        new
                        {
                            Id = 50,
                            Address = "Piano 6 Borgo Moretti 707, Gatti calabro, MN 93819",
                            CountryId = 5,
                            Name = "Alba Loch Resort",
                            Rating = 4.5999999999999996
                        },
                        new
                        {
                            Id = 51,
                            Address = "Puerta 141 Arroyo Berta Barreto, 13 Puerta 828, Bilbao, Com 48239",
                            CountryId = 6,
                            Name = "El Lago Sunrise Resort",
                            Rating = 4.9000000000000004
                        },
                        new
                        {
                            Id = 52,
                            Address = "Esc. 481 Rincon Pablo 5 Puerta 803, Santa Lucia de Tirajana, Ast 20510",
                            CountryId = 6,
                            Name = "Complejo Acantilado Esmeralda",
                            Rating = 4.5
                        },
                        new
                        {
                            Id = 53,
                            Address = "Muelle Benjamin, 22 Esc. 787, Calahorra, Can 09143",
                            CountryId = 6,
                            Name = "Hotel Panorama Otono",
                            Rating = 4.9000000000000004
                        },
                        new
                        {
                            Id = 54,
                            Address = "Puerta 112 Entrada Marta 9, Palencia, Ara 31531",
                            CountryId = 6,
                            Name = "Hotel Vacaciones",
                            Rating = 4.7000000000000002
                        },
                        new
                        {
                            Id = 55,
                            Address = "Esc. 129 Bloque Rosario 57 Esc. 931, Ponferrada, Cbr 48329",
                            CountryId = 6,
                            Name = "Actualizar Hotel",
                            Rating = 4.5999999999999996
                        },
                        new
                        {
                            Id = 56,
                            Address = "Plaza Dorotea 8, Tarrasa, Ast 25111",
                            CountryId = 6,
                            Name = "Tiempo Libre Resort Resort",
                            Rating = 4.5999999999999996
                        },
                        new
                        {
                            Id = 57,
                            Address = "Puerta 750 Riera Rosario 1, Almería, Bal 75211",
                            CountryId = 6,
                            Name = "Renacentista Hotel",
                            Rating = 4.4000000000000004
                        },
                        new
                        {
                            Id = 58,
                            Address = "Puerta 361 Sector Sancho 7 Esc. 557, Rivas-Vaciamadrid, Vas 42313",
                            CountryId = 6,
                            Name = "Campamento Verano Resort",
                            Rating = 4.2999999999999998
                        },
                        new
                        {
                            Id = 59,
                            Address = "Puerta 240 Travesia Monica, 48 Puerta 996, Torrevieja, Can 40461",
                            CountryId = 6,
                            Name = "Abismo Esmeralda Resort",
                            Rating = 4.5
                        },
                        new
                        {
                            Id = 60,
                            Address = "Esc. 348 Colonia Julia, 33, Alicante, Ast 85172",
                            CountryId = 6,
                            Name = "Grand Oak Resort & Spa",
                            Rating = 4.7000000000000002
                        },
                        new
                        {
                            Id = 61,
                            Address = "20 Grange Road, Doncaster, DN11 2VN",
                            CountryId = 7,
                            Name = "Eastern Star Hotel",
                            Rating = 4.2999999999999998
                        },
                        new
                        {
                            Id = 62,
                            Address = "89 Alexander Road, Redhill, RH71 6TU",
                            CountryId = 7,
                            Name = "Sunset Orb Resort & Spa",
                            Rating = 4.5999999999999996
                        },
                        new
                        {
                            Id = 63,
                            Address = "6 Grove Road, North London, N1 0ZD",
                            CountryId = 7,
                            Name = "Azure Heirloom Hotel",
                            Rating = 4.9000000000000004
                        },
                        new
                        {
                            Id = 64,
                            Address = "28 Kingsway, Kirkcaldy, KY32 0TH",
                            CountryId = 7,
                            Name = "Emerald Island Hotel",
                            Rating = 4.9000000000000004
                        },
                        new
                        {
                            Id = 65,
                            Address = "72 Park Avenue, Milton Keynes, MK2 0EB",
                            CountryId = 7,
                            Name = "Royal Echo Hotel",
                            Rating = 4.9000000000000004
                        },
                        new
                        {
                            Id = 66,
                            Address = "56 Richmond Road, Darlington, DL10 3GF",
                            CountryId = 7,
                            Name = "Coastline Hotel",
                            Rating = 4.9000000000000004
                        },
                        new
                        {
                            Id = 67,
                            Address = "9 New Street, Chelmsford, CM77 9VF",
                            CountryId = 7,
                            Name = "Light Sanctum Hotel",
                            Rating = 4.7999999999999998
                        },
                        new
                        {
                            Id = 68,
                            Address = "31 Park Avenue, Plymouth, PL7 6UG",
                            CountryId = 7,
                            Name = "Modest Nimbus Hotel",
                            Rating = 4.4000000000000004
                        },
                        new
                        {
                            Id = 69,
                            Address = "35 Park Lane, Wigan, WN45 6VI",
                            CountryId = 7,
                            Name = "Southern Maple Hotel",
                            Rating = 4.7000000000000002
                        },
                        new
                        {
                            Id = 70,
                            Address = "32 The Green, Crewe, CW12 7AP",
                            CountryId = 7,
                            Name = "Golden Raven Motel",
                            Rating = 4.4000000000000004
                        },
                        new
                        {
                            Id = 71,
                            Address = "Fridtjof-Nansen-Str. 77, Jaredberg, NI 50889",
                            CountryId = 8,
                            Name = "Lichtheiligtum Resort",
                            Rating = 4.5
                        },
                        new
                        {
                            Id = 72,
                            Address = "5 OG Steglitzer Str. 18c, Süd Marinaburg, HB 15290",
                            CountryId = 8,
                            Name = "Bescheidener Nimbus Hotel",
                            Rating = 5.0
                        },
                        new
                        {
                            Id = 73,
                            Address = "",
                            CountryId = 8,
                            Name = "Sudlicher Ahorn Hotel",
                            Rating = 4.5999999999999996
                        },
                        new
                        {
                            Id = 74,
                            Address = "3 OG Amselweg 69a, Grimmstadt, MV 33837",
                            CountryId = 8,
                            Name = "Goldener Rabe Hotel",
                            Rating = 4.5
                        },
                        new
                        {
                            Id = 75,
                            Address = "",
                            CountryId = 8,
                            Name = "Silbernes Universum Resort",
                            Rating = 4.7999999999999998
                        },
                        new
                        {
                            Id = 76,
                            Address = "Maria-Terwiel-Str. 14c, Ost Steffenhagen, MV 92427",
                            CountryId = 8,
                            Name = "Herrenpalast Resort",
                            Rating = 4.5999999999999996
                        },
                        new
                        {
                            Id = 77,
                            Address = "",
                            CountryId = 8,
                            Name = "Orientalisches Hotel",
                            Rating = 4.2999999999999998
                        },
                        new
                        {
                            Id = 78,
                            Address = "6 OG Ehrlichstr. 68a, Greenbrunn, BE 21295",
                            CountryId = 8,
                            Name = "Sternenlicht Resort",
                            Rating = 4.2999999999999998
                        },
                        new
                        {
                            Id = 79,
                            Address = "Odenthaler Str. 4, Bad Dennis, HE 12691",
                            CountryId = 8,
                            Name = "Herrliches Vista Hotel",
                            Rating = 4.7000000000000002
                        },
                        new
                        {
                            Id = 80,
                            Address = "Niederblecher 70, Bad Vanessa, HB 62368",
                            CountryId = 8,
                            Name = "Majestatischer Hotel & Spa",
                            Rating = 4.9000000000000004
                        },
                        new
                        {
                            Id = 81,
                            Address = "Kolokotroni 16, Thessaloniki, Central Macedonia 564 30",
                            CountryId = 9,
                            Name = "Eleftherios Garden Hotel",
                            Rating = 4.2999999999999998
                        },
                        new
                        {
                            Id = 82,
                            Address = "Patmos Island, Patmos, South Aegean 855 00",
                            CountryId = 9,
                            Name = "Zervakos Hotel & Spa",
                            Rating = 4.9000000000000004
                        },
                        new
                        {
                            Id = 83,
                            Address = " Negri Fokionos 80, Athina, Attica 113 61",
                            CountryId = 9,
                            Name = "Gavriil Resort",
                            Rating = 4.5
                        },
                        new
                        {
                            Id = 84,
                            Address = "Riga Fereou,  Kalamata, Peloponnese 241 00",
                            CountryId = 9,
                            Name = "Fotini Pateroti Resort",
                            Rating = 4.7000000000000002
                        },
                        new
                        {
                            Id = 85,
                            Address = "Leoforos Mesogeion 59, Athina, Attica 115 26",
                            CountryId = 9,
                            Name = "Gianna Mundelli Hotel",
                            Rating = 4.7000000000000002
                        },
                        new
                        {
                            Id = 86,
                            Address = "Gravias 6, Agia Paraskevi, Attica 153 42",
                            CountryId = 9,
                            Name = "Florentia Hotel",
                            Rating = 4.4000000000000004
                        },
                        new
                        {
                            Id = 87,
                            Address = "25is Martiou 10, Edessa, Central Macedonia 582 00",
                            CountryId = 9,
                            Name = "Ismini Milea Resort",
                            Rating = 4.4000000000000004
                        },
                        new
                        {
                            Id = 88,
                            Address = "Megalou Alexandrou 70, Athina, Attica 171 22",
                            CountryId = 9,
                            Name = "Yanna Galanidi Boutique Hotel",
                            Rating = 4.7000000000000002
                        },
                        new
                        {
                            Id = 89,
                            Address = "Eleftheriou Venizelou 26, Kavala, Thrace 653 02",
                            CountryId = 9,
                            Name = "Rania Romana Regency",
                            Rating = 4.4000000000000004
                        },
                        new
                        {
                            Id = 90,
                            Address = "Platia Theatrou 2, Athina, Attica 105 52",
                            CountryId = 9,
                            Name = "Kalliopi Kanea Villas & Guesthouses",
                            Rating = 4.5999999999999996
                        },
                        new
                        {
                            Id = 91,
                            Address = "192 Holzgasse, Gemeinde Klosterneuburg, Bezirk Tulln, Lower Austria 3400",
                            CountryId = 10,
                            Name = "Mondlicht Resort",
                            Rating = 4.7000000000000002
                        },
                        new
                        {
                            Id = 92,
                            Address = "2 Ohmgasse, Vienna 1210",
                            CountryId = 10,
                            Name = "Golden Flustern Villas & Guesthouses",
                            Rating = 4.9000000000000004
                        },
                        new
                        {
                            Id = 93,
                            Address = "210 Greit, Bezirk Landeck, Tyrol 6542",
                            CountryId = 10,
                            Name = "Koniglich Harmonie",
                            Rating = 4.5
                        },
                        new
                        {
                            Id = 94,
                            Address = "3 Waldegghofgasse, Vienna 1170",
                            CountryId = 10,
                            Name = "Funkeln Diamant Resort & Spa",
                            Rating = 4.5999999999999996
                        },
                        new
                        {
                            Id = 95,
                            Address = "4 Overbeckgasse, Siedlung Auhofer, Vienna 1130",
                            CountryId = 10,
                            Name = "Azure Erheben Hotel",
                            Rating = 4.5999999999999996
                        },
                        new
                        {
                            Id = 96,
                            Address = "Gemeinde Ardagger, Bezirk Amstetten, Lower Austria 3321",
                            CountryId = 10,
                            Name = "Elegant Urlaub",
                            Rating = 5.0
                        },
                        new
                        {
                            Id = 97,
                            Address = "5-7 Primavesigasse, Donaustadt, Vienna 1220",
                            CountryId = 10,
                            Name = "Strahlend Himmel Hotel",
                            Rating = 4.7000000000000002
                        },
                        new
                        {
                            Id = 98,
                            Address = "33 Trauttmansdorffgasse, Vienna 1130",
                            CountryId = 10,
                            Name = "Luxus Golden Hotel",
                            Rating = 4.4000000000000004
                        },
                        new
                        {
                            Id = 99,
                            Address = "32 Pomedt, Bezirk Scharding, Upper Austria 4752 ",
                            CountryId = 10,
                            Name = "Royal Oasis Hotel",
                            Rating = 4.7999999999999998
                        },
                        new
                        {
                            Id = 100,
                            Address = "7 Bahngasse, Bezirk Oberpullendorf, Burgenland 7451",
                            CountryId = 10,
                            Name = "Elegant Komfort Hotel",
                            Rating = 4.5
                        });
                });

            modelBuilder.Entity("HotelListing.API.Data.Hotel", b =>
                {
                    b.HasOne("HotelListing.API.Data.Country", "Country")
                        .WithMany("Hotels")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("HotelListing.API.Data.Country", b =>
                {
                    b.Navigation("Hotels");
                });
#pragma warning restore 612, 618
        }
    }
}
